In [3]:
import numpy as np
import pandas as pd

In [4]:
dvk=pd.read_csv('series_kohli_ipl.csv')
#print(dvk)
svk=dvk['runs']
print(svk)
type(svk)

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

pandas.Series

In [5]:
# ### Q1. Create a Pandas Series from a list of integers.
# > 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

l=[1,2,3,4,5]
s1=pd.Series(l)
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# ### Q2. Create a Series from a dictionary with custom index.
# > 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.
dict1={'name': 'Arun','age':36,'salary':15000}
s2=pd.Series(dict1)
print(s2)

name       Arun
age          36
salary    15000
dtype: object

In [7]:
# ### Q3. Access elements using index labels.
# > 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

ser = pd.Series(['arun','bob','chaya','dev','ellyse','frank'],index=['a','b','c','d','e','f'])
print(ser['b'])
print(ser[['a','c']])
print(ser['a':'d'])

bob
a     arun
c    chaya
dtype: str
a     arun
b      bob
c    chaya
d      dev
dtype: str

In [8]:
# ### Q4. Perform arithmetic operations on a Series.
# > 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.
print(s1)
print(s1+10)
print(s1*10)
print(s1//10)
print(s1**2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    11
1    12
2    13
3    14
4    15
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64
0     1
1     4
2     9
3    16
4    25
dtype: int64

In [9]:
# ### Q5. Find mean, min, max of a Series.
# > 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.
print(s1)
print(s1.mean())
print(s1.median())
print(s1.min())
print(s1.max())
print(s1.std())
print(s1.var())

0    1
1    2
2    3
3    4
4    5
dtype: int64
3.0
3.0
1
5
1.5811388300841898
2.5

In [10]:
# ### Q6. Apply conditional filtering on a Series.
# > 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

#print(svk[(svk>50) & (svk<90)])
print(svk[(svk==50) | (svk==30)])

14     50
42     30
145    30
181    50
209    30
Name: runs, dtype: int64

In [11]:
# ### Q7. Replace values in a Series.
# > 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.
s1
print(s1.replace(1,100))
print(s1.replace({1:10,3:30}))

0    100
1      2
2      3
3      4
4      5
dtype: int64
0    10
1     2
2    30
3     4
4     5
dtype: int64

In [12]:
# ### Q8. Convert Series data type.
# > 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.
s1.dtype
s1=s1.astype('int32')
s1.dtype

dtype('int32')

In [13]:
# ### Q9. Check for null values in Series.
# > 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

s9=pd.Series([1,2,np.nan,3,np.nan,np.nan,4,np.nan])
print(s9)
print(s9.isnull())
print(s9.isnull().sum())

0    1.0
1    2.0
2    NaN
3    3.0
4    NaN
5    NaN
6    4.0
7    NaN
dtype: float64
0    False
1    False
2     True
3    False
4     True
5     True
6    False
7     True
dtype: bool
4

In [14]:
# ### Q10. Fill missing values in Series.
# > 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

s9
print(s9.fillna(25))
print(s9.ffill())
print(s9.bfill())

0     1.0
1     2.0
2    25.0
3     3.0
4    25.0
5    25.0
6     4.0
7    25.0
dtype: float64
0    1.0
1    2.0
2    2.0
3    3.0
4    3.0
5    3.0
6    4.0
7    4.0
dtype: float64
0    1.0
1    2.0
2    3.0
3    3.0
4    4.0
5    4.0
6    4.0
7    NaN
dtype: float64

In [15]:
# ### Q11. Create DataFrame from a list.
# > 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.
student_mark=[[67,56,54,56,55],
              [63,65,67,48,78],
              [89,56,27,48,62],
              [98,85,75,95,84]]

df1=pd.DataFrame(student_mark,columns=['hindi','english','science','maths','sst'])
df1

   hindi  english  science  maths  sst
0     67       56       54     56   55
1     63       65       67     48   78
2     89       56       27     48   62
3     98       85       75     95   84

In [16]:
# ### Q12. Create DataFrame from a dictionary.
# > 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

dict={'name':['Shubham','Dev','Ram','Ishan'],'age':[29,36,45,26],'gender':['m','m','m','m']}
df2=pd.DataFrame(dict)
df2

      name  age gender
0  Shubham   29      m
1      Dev   36      m
2      Ram   45      m
3    Ishan   26      m

In [17]:
# ### Q13. Create DataFrame from list of dictionaries.
# > 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

data = [
    {'match_no': 1, 'runs': 34},
    {'match_no': 2, 'runs': 56},
    {'match_no': 3, 'runs': 78},
    {'match_no': 4}
]
df3=pd.DataFrame(data)
df3

   match_no  runs
0         1  34.0
1         2  56.0
2         3  78.0
3         4   NaN

In [18]:
# ### Q14. Display DataFrame structure (shape, columns, dtypes).
# > 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.
print(df3.shape)
print()
print(df3.columns)
print()
print(df3.dtypes)
print()
print(df3.info())
print()
print(df3.describe())

(4, 2)

Index(['match_no', 'runs'], dtype='str')

match_no      int64
runs        float64
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   match_no  4 non-null      int64
 1   runs      3 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 196.0 bytes
None

       match_no  runs
count  4.000000   3.0
mean   2.500000  56.0
std    1.290994  22.0
min    1.000000  34.0
25%    1.750000  45.0
50%    2.500000  56.0
75%    3.250000  67.0
max    4.000000  78.0

In [19]:
# ### Q15. Select single column from DataFrame.
# > 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).
print(df3['match_no'])
print(df3.match_no)

0    1
1    2
2    3
3    4
Name: match_no, dtype: int64
0    1
1    2
2    3
3    4
Name: match_no, dtype: int64

In [20]:
# ### Q16. Select multiple columns.
# > 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.
df1
x=df1[['hindi','english']]
x

   hindi  english
0     67       56
1     63       65
2     89       56
3     98       85

In [21]:
# ### Q17. Add new column with scalar value.
# > 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.
df1['evs']=65
df1

   hindi  english  science  maths  sst  evs
0     67       56       54     56   55   65
1     63       65       67     48   78   65
2     89       56       27     48   62   65
3     98       85       75     95   84   65

In [22]:
# ### Q18. Add column using Series.
# > 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.
df1['marathi']=[89,88,85,86]
df1

   hindi  english  science  maths  sst  evs  marathi
0     67       56       54     56   55   65       89
1     63       65       67     48   78   65       88
2     89       56       27     48   62   65       85
3     98       85       75     95   84   65       86

In [23]:
# ### Q19. Rename columns using `rename()`.
# > 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

df1.rename(columns={'hindi':'HINDI'},inplace=1)
df1

   HINDI  english  science  maths  sst  evs  marathi
0     67       56       54     56   55   65       89
1     63       65       67     48   78   65       88
2     89       56       27     48   62   65       85
3     98       85       75     95   84   65       86

In [24]:
# ### Q20. Rename multiple columns.
# > 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.
df1.rename(columns={'english':'ENGLISH','maths':'MATHS'},inplace=1)
df1

   HINDI  ENGLISH  science  MATHS  sst  evs  marathi
0     67       56       54     56   55   65       89
1     63       65       67     48   78   65       88
2     89       56       27     48   62   65       85
3     98       85       75     95   84   65       86

In [25]:
df1['name']=['s1','s2','s3','s4']
df1.set_index('name',inplace=True)
df1

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

In [26]:
# ### Q21. Select rows using `loc`.
# > 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**
print(df1.loc['s1'])
print()
print(df1.loc['s1':'s3'])
print()

HINDI      67
ENGLISH    56
science    54
MATHS      56
sst        55
evs        65
marathi    89
Name: s1, dtype: int64

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85

In [27]:
# ### Q22. Select rows using `iloc`.
# > 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).
print(df1.iloc[1])
print()
print(df1.iloc[1:4])
print()

HINDI      63
ENGLISH    65
science    67
MATHS      48
sst        78
evs        65
marathi    88
Name: s2, dtype: int64

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

In [28]:
# ### Q23. Access specific row and column.
# > 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.
print(df1.loc['s1', 'MATHS'])
print(df1.iloc[0, 3])

56
56

In [29]:
# ### Q24. Select subset using multiple rows & columns.
# > 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.
print(df1.loc[['s1','s3'], ['MATHS','sst']])
print(df1.iloc[[0,1], [0,3]])

      MATHS  sst
name
s1       56   55
s3       48   62
      HINDI  MATHS
name
s1       67     56
s2       63     48

In [30]:
# ### Q25. Apply conditional filtering using `loc`.
# > 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

df1.loc[df1["sst"] > 65, ["MATHS","sst"]]

      MATHS  sst
name
s2       48   78
s4       95   84

In [31]:
# ### Q26. Slice rows using index range.
# > 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

df1.iloc[0:3]
df1.loc['s1':'s3']

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85

In [32]:
# ### Q27. Slice columns using labels.
# > 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).
print(df1.loc[:,'science':'evs'])

      science  MATHS  sst  evs
name
s1         54     56   55   65
s2         67     48   78   65
s3         27     48   62   65
s4         75     95   84   65

In [33]:
# ### Q28. Slice columns using position.
# > 💡 **Hint:** `df.iloc[start:end]` — selects all rows, columns at positions 1, 2, 3.
print(df1.iloc[:,1:4])

      ENGLISH  science  MATHS
name
s1         56       54     56
s2         65       67     48
s3         56       27     48
s4         85       75     95

In [34]:
# ### Q29. Perform combined row & column slicing.
# > 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

df1.loc['s1':'s3',['MATHS','evs']]
df1.iloc[0:2, [0, 2, 4]]

      HINDI  science  sst
name
s1       67       54   55
s2       63       67   78

In [35]:
# # ### Q30. Set a column as index.
# # > 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.


# df1['name']=['s1','s2','s3','s4']
# df1.set_index('name',inplace=True)
# df1

In [36]:
# ### Q31. Create hierarchical index (MultiIndex).
# > 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

df = pd.DataFrame({
    'country': ['India', 'India', 'USA'],
    'city': ['Mumbai', 'Delhi', 'New York'],
    'population': [20, 19, 8]
})

df4 = df.set_index(['country', 'city'])
df4

                  population
country city
India   Mumbai            20
        Delhi             19
USA     New York           8

In [37]:
# ### Q32. Reset index.
# > 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

df4.reset_index(inplace=True)
df4

  country      city  population
0   India    Mumbai          20
1   India     Delhi          19
2     USA  New York           8

In [38]:
# ### Q33. Reset multi-index.
# > 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

df4.reset_index(inplace=True)
df4

   index country      city  population
0      0   India    Mumbai          20
1      1   India     Delhi          19
2      2     USA  New York           8

In [39]:
# ### Q34. Convert index to column.
# > 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.
print(df4.reset_index(drop=False))

   level_0  index country      city  population
0        0      0   India    Mumbai          20
1        1      1   India     Delhi          19
2        2      2     USA  New York           8

In [40]:
# ### Q35. Use drop option in `reset_index`.
# > 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.
df4
print(df4.reset_index(drop=True))

   index country      city  population
0      0   India    Mumbai          20
1      1   India     Delhi          19
2      2     USA  New York           8

In [41]:
# ### Q36. Perform label-based indexing.
# > 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).
df1.loc['s3']

HINDI      89
ENGLISH    56
science    27
MATHS      48
sst        62
evs        65
marathi    85
Name: s3, dtype: int64

In [42]:
# ### Q37. Perform position-based indexing.
# > 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.
df1.iloc[3]

HINDI      98
ENGLISH    85
science    75
MATHS      95
sst        84
evs        65
marathi    86
Name: s4, dtype: int64

In [43]:
# ### Q38. Access first N rows.
# > 💡 **Hint:** `df.head(N)` — default N is 5.
df1.head(3)

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85

In [44]:
# ### Q39. Access last N rows.
# > 💡 **Hint:** `df.tail(N)` — default N is 5.
df1.tail(3)

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

In [45]:
# ### Q40. Extract random sample from DataFrame.
# > 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.
dvk.sample(6)

     match_no  runs
190       191    35
91         92    35
196       197    51
151       152    70
187       188    72
118       119    80

In [46]:
print(dvk.sample(frac=.01))
print(dvk.shape)

    match_no  runs
56        57    57
6          7    34
(215, 2)

In [47]:
# ### Q41. Detect missing values using `isnull()`.
# > 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.
print(df3.isnull())
print(df3.isnull().sum())
print(df3.isnull().any())

   match_no   runs
0     False  False
1     False  False
2     False  False
3     False   True
match_no    0
runs        1
dtype: int64
match_no    False
runs         True
dtype: bool

In [48]:
# ### Q42. Drop missing values using `dropna()`.
# > 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

print(df3.dropna())
print(df3.dropna(axis=1))
print(df3.dropna(subset=["match_no"]))
print(df3.dropna(thresh=2))

   match_no  runs
0         1  34.0
1         2  56.0
2         3  78.0
   match_no
0         1
1         2
2         3
3         4
   match_no  runs
0         1  34.0
1         2  56.0
2         3  78.0
3         4   NaN
   match_no  runs
0         1  34.0
1         2  56.0
2         3  78.0

In [49]:
# ### Q43. Fill missing values with a constant.
# > 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.
df5 = pd.DataFrame({
    'A': [1, np.nan, 3, np.nan],
    'B': [4, 5, np.nan, np.nan],
    'C': [7, np.nan, 9, 10]
})

df5
print(df5.fillna(50))
print(df5['A'].fillna(10))
print(df5.fillna({'A':10,'B':20,'C':30}))

      A     B     C
0   1.0   4.0   7.0
1  50.0   5.0  50.0
2   3.0  50.0   9.0
3  50.0  50.0  10.0
0     1.0
1    10.0
2     3.0
3    10.0
Name: A, dtype: float64
      A     B     C
0   1.0   4.0   7.0
1  10.0   5.0  30.0
2   3.0  20.0   9.0
3  10.0  20.0  10.0

In [50]:
# ### Q44. Fill missing values using mean/median.
# > 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.
print(df5["A"].fillna(df5["A"].mean()))
print(df5.fillna(df5.mean()))
print(df5["C"].fillna(df5["C"].median()))

0    1.0
1    2.0
2    3.0
3    2.0
Name: A, dtype: float64
     A    B          C
0  1.0  4.0   7.000000
1  2.0  5.0   8.666667
2  3.0  4.5   9.000000
3  2.0  4.5  10.000000
0     7.0
1     9.0
2     9.0
3    10.0
Name: C, dtype: float64

In [51]:
# ### Q45. Use forward fill and backward fill.
# > 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.
print(df5.ffill())
print(df5.bfill())

     A    B     C
0  1.0  4.0   7.0
1  1.0  5.0   7.0
2  3.0  5.0   9.0
3  3.0  5.0  10.0
     A    B     C
0  1.0  4.0   7.0
1  3.0  5.0   9.0
2  3.0  NaN   9.0
3  NaN  NaN  10.0

In [52]:
# ### Q46. Convert data type using `astype()`.
# > 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.
print(df5['A'].dtype)
print(df5['A'].astype('float32'))

df46 = pd.DataFrame({
    "marks": ["90", "85", "abc", "75"]
})
print(df46)
df46["marks"] = pd.to_numeric(df46["marks"], errors="coerce")
print(df46)

float64
0    1.0
1    NaN
2    3.0
3    NaN
Name: A, dtype: float32
  marks
0    90
1    85
2   abc
3    75
   marks
0   90.0
1   85.0
2    NaN
3   75.0

In [53]:

# ### Q47. Clean string column using `.str.lower()`.
# > 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.
df2
print(df2['name'].str.lower())
print(df2['name'].str.upper())
print(df2['name'].str.title())

0    shubham
1        dev
2        ram
3      ishan
Name: name, dtype: str
0    SHUBHAM
1        DEV
2        RAM
3      ISHAN
Name: name, dtype: str
0    Shubham
1        Dev
2        Ram
3      Ishan
Name: name, dtype: str

In [54]:
# ### Q48. Trim whitespace in strings.
# > 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.
print(df2['name'].str.strip())
print(df2['name'].str.lstrip())
print(df2['name'].str.rstrip())

0    Shubham
1        Dev
2        Ram
3      Ishan
Name: name, dtype: str
0    Shubham
1        Dev
2        Ram
3      Ishan
Name: name, dtype: str
0    Shubham
1        Dev
2        Ram
3      Ishan
Name: name, dtype: str

In [55]:
# ### Q49. Replace substring in column.
# > 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.
print(df2['name'].str.replace("Dev","David"))

0    Shubham
1      David
2        Ram
3      Ishan
Name: name, dtype: str

In [56]:
df10 = pd.DataFrame({
    "name": [
        "Amit Sharma", "Priya Verma", "Rahul Singh", "Neha Gupta",
        "Amit Sharma", "Karan Mehta", "Sneha Patel", "Rahul Singh",
        "Vikram Joshi", "Anjali Rao"
    ],
    "age": [
        28, 32, 25, 29,
        28, 35, 27, 25,
        40, 31
    ],
    "email": [
        "amit@gmail.com", "priya@gmail.com", "rahul@gmail.com", "neha@gmail.com",
        "amit@gmail.com", "karan@gmail.com", "sneha@gmail.com", "rahul@gmail.com",
        "vikram@gmail.com", "anjali@gmail.com"
    ],
    "salary": [
        50000, 65000, 45000, 55000,
        50000, 80000, 48000, 45000,
        90000, 62000
    ],
    "job": [
        "Developer", "Analyst", "Developer", "Manager",
        "Developer", "Manager", "Designer", "Developer",
        "Director", "Analyst"
    ],
    "location": [
        "Mumbai", "Pune", "Delhi", "Bangalore",
        "Mumbai", "Hyderabad", "Pune", "Delhi",
        "Chennai", "Mumbai"
    ]
})
df10

           name  age             email  salary        job   location
0   Amit Sharma   28    amit@gmail.com   50000  Developer     Mumbai
1   Priya Verma   32   priya@gmail.com   65000    Analyst       Pune
2   Rahul Singh   25   rahul@gmail.com   45000  Developer      Delhi
3    Neha Gupta   29    neha@gmail.com   55000    Manager  Bangalore
4   Amit Sharma   28    amit@gmail.com   50000  Developer     Mumbai
5   Karan Mehta   35   karan@gmail.com   80000    Manager  Hyderabad
6   Sneha Patel   27   sneha@gmail.com   48000   Designer       Pune
7   Rahul Singh   25   rahul@gmail.com   45000  Developer      Delhi
8  Vikram Joshi   40  vikram@gmail.com   90000   Director    Chennai
9    Anjali Rao   31  anjali@gmail.com   62000    Analyst     Mumbai

In [57]:
# ### Q50. Extract part of string using `.str`.
# > 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.
print(df2['name'].str[:3])
print(df10['email'].str.split("@").str[1])

0    Shu
1    Dev
2    Ram
3    Ish
Name: name, dtype: str
0    gmail.com
1    gmail.com
2    gmail.com
3    gmail.com
4    gmail.com
5    gmail.com
6    gmail.com
7    gmail.com
8    gmail.com
9    gmail.com
Name: email, dtype: object

In [58]:
# ### Q51. Detect duplicate rows.
# > 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.
print(df10.duplicated())
print(df10[df10.duplicated()])

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8    False
9    False
dtype: bool
          name  age            email  salary        job location
4  Amit Sharma   28   amit@gmail.com   50000  Developer   Mumbai
7  Rahul Singh   25  rahul@gmail.com   45000  Developer    Delhi

In [59]:
# ### Q52. Remove duplicates using `drop_duplicates()`.
# > 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

df10.drop_duplicates()
df10.drop_duplicates(subset=['job'])
df10.drop_duplicates(subset=['job'],keep='last')
df10.drop_duplicates(subset=['job'],keep=False)

           name  age             email  salary       job location
6   Sneha Patel   27   sneha@gmail.com   48000  Designer     Pune
8  Vikram Joshi   40  vikram@gmail.com   90000  Director  Chennai

In [60]:
# ### Q53. Rename row labels.
# > 💡 **Hint:** `df.rename(index={old_label: new_label})`.

print(df1.rename(index={'s1':'m1'}))

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
m1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

In [61]:
# ### Q54. Handle inconsistent data.
# > 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.
df = pd.DataFrame({
    "job": [
        "Developer",
        "dev",
        "DEV",
        "developer",
        "Developer "
    ]
})
df["job"] = df["job"].str.strip().str.lower()
df["job"] = df["job"].replace({"dev": "developer"})
df

         job
0  developer
1  developer
2  developer
3  developer
4  developer

In [62]:
# ### Q55. Replace values in DataFrame.
# > 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.
df["job"] = df["job"].replace({"dev": "developer"})

In [63]:

# ### Q56. Detect outliers in a column.
# > 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

df = pd.DataFrame({ "salary": [45000, 50000, 52000, 55000, 5020, 58000, 60000, 250000]})
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df["salary"] < lower) | (df["salary"] > upper)]
print(outliers)

   salary
4    5020
7  250000

In [64]:
mean = df["salary"].mean()
std = df["salary"].std()
df["zscore"] = (df["salary"] - mean) / std
outliers = df[abs(df["zscore"]) > 3]
print(outliers)
df

Empty DataFrame
Columns: [salary, zscore]
Index: []

   salary    zscore
0   45000 -0.362830
1   50000 -0.295333
2   52000 -0.268334
3   55000 -0.227836
4    5020 -0.902536
5   58000 -0.187338
6   60000 -0.160339
7  250000  2.404547

In [65]:
# ### Q57. Handle outliers using clipping.
# > 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.
print(df1)
df1["science"].clip(lower=40, upper=70)

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

name
s1    54
s2    67
s3    40
s4    70
Name: science, dtype: int64

In [66]:
# ### Q58. Standardize column names.
# > 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.
print(df1.columns.str.strip().str.lower().str.replace(" ", "_"))

Index(['hindi', 'english', 'science', 'maths', 'sst', 'evs', 'marathi'], dtype='str')

In [67]:
# ### Q59. Handle mixed data types in a column.
# > 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.
df46 = pd.DataFrame({"marks": ["90", "85", "abc", "75"]})
print(df46)
pd.to_numeric(df46["marks"], errors="coerce")
print(df46)

  marks
0    90
1    85
2   abc
3    75
  marks
0    90
1    85
2   abc
3    75

In [68]:
# ### Q60. Remove special characters from text data.
# > 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.
df10["email"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

0      amitgmailcom
1     priyagmailcom
2     rahulgmailcom
3      nehagmailcom
4      amitgmailcom
5     karangmailcom
6     snehagmailcom
7     rahulgmailcom
8    vikramgmailcom
9    anjaligmailcom
Name: email, dtype: str

In [110]:
# ### Q61. Filter rows using AND condition.
# > 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.
df1
df1[(df1["HINDI"] > 85) & (df1["MATHS"] == 48)]

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s3       89       56       27     48   62   65       85

In [111]:
# ### Q62. Filter rows using OR condition.
# > 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.
df1[(df1["HINDI"] > 85) | (df1["MATHS"] == 48)]

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

In [112]:
# ### Q63. Filter rows using NOT condition.
# > 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.
df1[~(df1["MATHS"] == 48)]

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s4       98       85       75     95   84   65       86

In [118]:
# ### Q64. Sort DataFrame by column values.
# > 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.
df1.sort_values("sst",ascending=False)

print(df1.sort_values(by=['MATHS',"sst"],ascending=False))

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s4       98       85       75     95   84   65       86
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85

In [123]:
# ### Q65. Sort DataFrame by index.
# > 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.
df1.sort_index(axis=1)

      ENGLISH  HINDI  MATHS  evs  marathi  science  sst
name
s1         56     67     56   65       89       54   55
s2         65     63     48   65       88       67   78
s3         56     89     48   65       85       27   62
s4         85     98     95   65       86       75   84

In [125]:
# ### Q66. Add calculated column.
# > 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.
df1['total']=df1['HINDI']+df1["ENGLISH"]
df1

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi  total
name
s1       67       56       54     56   55   65       89    123
s2       63       65       67     48   78   65       88    128
s3       89       56       27     48   62   65       85    145
s4       98       85       75     95   84   65       86    183

In [139]:
# ### Q67. Remove column using `drop()`.
# > 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.
df1.drop(columns=['total'],inplace=True)

In [140]:
# ### Q68. Remove rows using `drop()`.
# > 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.
df1.drop(index=['s1','s3'])

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s2       63       65       67     48   78   65       88
s4       98       85       75     95   84   65       86

In [ ]:
# ### Q69. Use `map()` on a column.
# > 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.
df1["sst"].map({78: 87, 84: 48})
df1["sst"].map(lambda x: '')

name
s1    60
s2    83
s3    67
s4    89
Name: sst, dtype: int64

In [145]:
# ### Q70. Apply function using `apply()`.
# > 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.
print(df1)
df1["evs"].apply(lambda x:x+10)
df1.apply(sum,axis=1)
df1.apply(sum,axis=0)

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

HINDI      317
ENGLISH    262
science    223
MATHS      247
sst        279
evs        260
marathi    348
dtype: int64

In [148]:
# ### Q71. Apply element-wise using `applymap()` / `map()`.
# > 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.
#df1.applymap(sum)
df1.map(lambda x:x*2)

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1      134      112      108    112  110  130      178
s2      126      130      134     96  156  130      176
s3      178      112       54     96  124  130      170
s4      196      170      150    190  168  130      172

In [152]:
# ### Q72. Chain multiple operations.
# > 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.
df10['age'].iloc[2:8].sort_values().map(lambda x:x*2)

2    50
7    50
6    54
4    56
3    58
5    70
Name: age, dtype: int64

In [153]:
# ### Q73. Normalize numeric columns (Min-Max).
# > 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].
(df1["sst"] - df1["sst"].min()) / (df1["sst"].max() - df1["sst"].min())

name
s1    0.000000
s2    0.793103
s3    0.241379
s4    1.000000
Name: sst, dtype: float64

In [156]:
# ### Q74. Scale numerical data (Z-score standardization).
# > 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.
(df1["sst"] - df1["sst"].mean()) / df1["sst"].std()
print(((df1["sst"] - df1["sst"].mean()) / df1["sst"].std()).mean())
print(((df1["sst"] - df1["sst"].mean()) / df1["sst"].std()).std())

-5.551115123125783e-17
1.0

In [160]:
# ### Q75. Rank values in a column.
# > 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.
print(df1['MATHS'].rank())
print(df1['MATHS'].rank(method='dense'))

name
s1    3.0
s2    1.5
s3    1.5
s4    4.0
Name: MATHS, dtype: float64
name
s1    2.0
s2    1.0
s3    1.0
s4    3.0
Name: MATHS, dtype: float64

In [164]:
df1

      HINDI  ENGLISH  science  MATHS  sst  evs  marathi
name
s1       67       56       54     56   55   65       89
s2       63       65       67     48   78   65       88
s3       89       56       27     48   62   65       85
s4       98       85       75     95   84   65       86

In [167]:
# ### Q76. Create bins using `cut()`.
# > 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.
r1=pd.cut(df1['science'],bins=4)
r1
pd.cut(df1["MATHS"], bins=[0,50,100], labels=["Low","High"])

name
s1    High
s2     Low
s3     Low
s4    High
Name: MATHS, dtype: category
Categories (2, str): ['Low' < 'High']

In [171]:
# ### Q77. Create bins using `qcut()`.
# > 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.
pd.qcut(df1["HINDI"], q=4)

name
s1      (66.0, 78.0]
s2    (62.999, 66.0]
s3     (78.0, 91.25]
s4     (91.25, 98.0]
Name: HINDI, dtype: category
Categories (4, interval[float64, right]): [(62.999, 66.0] < (66.0, 78.0] < (78.0, 91.25] < (91.25, 98.0]]

In [174]:
# ### Q78. Count unique values.
# > 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.
df10["age"].nunique()
df10["age"].value_counts()

age
28    2
25    2
32    1
29    1
35    1
27    1
40    1
31    1
Name: count, dtype: int64

In [178]:
# ### Q79. Replace multiple values at once.
# > 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.
df10.replace({'age':{28:280,32:320}})
df10.replace([28,32,65000],00)

           name  age             email  salary        job   location
0   Amit Sharma    0    amit@gmail.com   50000  Developer     Mumbai
1   Priya Verma    0   priya@gmail.com       0    Analyst       Pune
2   Rahul Singh   25   rahul@gmail.com   45000  Developer      Delhi
3    Neha Gupta   29    neha@gmail.com   55000    Manager  Bangalore
4   Amit Sharma    0    amit@gmail.com   50000  Developer     Mumbai
5   Karan Mehta   35   karan@gmail.com   80000    Manager  Hyderabad
6   Sneha Patel   27   sneha@gmail.com   48000   Designer       Pune
7   Rahul Singh   25   rahul@gmail.com   45000  Developer      Delhi
8  Vikram Joshi   40  vikram@gmail.com   90000   Director    Chennai
9    Anjali Rao   31  anjali@gmail.com   62000    Analyst     Mumbai

In [181]:
# ### Q80. Create flag column based on condition.
# > 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.
df10["flag"] = (df10["age"] > 30).astype(int)
df10

           name  age             email  salary        job   location  flag
0   Amit Sharma   28    amit@gmail.com   50000  Developer     Mumbai     0
1   Priya Verma   32   priya@gmail.com   65000    Analyst       Pune     1
2   Rahul Singh   25   rahul@gmail.com   45000  Developer      Delhi     0
3    Neha Gupta   29    neha@gmail.com   55000    Manager  Bangalore     0
4   Amit Sharma   28    amit@gmail.com   50000  Developer     Mumbai     0
5   Karan Mehta   35   karan@gmail.com   80000    Manager  Hyderabad     1
6   Sneha Patel   27   sneha@gmail.com   48000   Designer       Pune     0
7   Rahul Singh   25   rahul@gmail.com   45000  Developer      Delhi     0
8  Vikram Joshi   40  vikram@gmail.com   90000   Director    Chennai     1
9    Anjali Rao   31  anjali@gmail.com   62000    Analyst     Mumbai     1

In [188]:
# ### Q81. Iterate over rows using `iterrows()`.
# > 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.
for idx, row in df1.iterrows():
    print(idx)
    print(row)

s1
HINDI      67
ENGLISH    56
science    54
MATHS      56
sst        55
evs        65
marathi    89
Name: s1, dtype: int64
s2
HINDI      63
ENGLISH    65
science    67
MATHS      48
sst        78
evs        65
marathi    88
Name: s2, dtype: int64
s3
HINDI      89
ENGLISH    56
science    27
MATHS      48
sst        62
evs        65
marathi    85
Name: s3, dtype: int64
s4
HINDI      98
ENGLISH    85
science    75
MATHS      95
sst        84
evs        65
marathi    86
Name: s4, dtype: int64

In [191]:
# ### Q82. Iterate using `itertuples()`.
# > 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.
for row in df1.itertuples():
    print(row.HINDI)

67
63
89
98

In [194]:
# ### Q83. Iterate over columns.
# > 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.
for col in df1.columns:
    print(col)

HINDI
ENGLISH
science
MATHS
sst
evs
marathi

In [182]:
# ### Q84. Avoid iteration using vectorization.
# > 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.
df10["new"] = df10["age"] * 2 + 1
df10

,name,age,email,salary,job,location,flag,new
0,Amit Sharma,28,amit@gmail.com,50000,Developer,Mumbai,0,57
1,Priya Verma,32,priya@gmail.com,65000,Analyst,Pune,1,65
2,Rahul Singh,25,rahul@gmail.com,45000,Developer,Delhi,0,51
3,Neha Gupta,29,neha@gmail.com,55000,Manager,Bangalore,0,59
4,Amit Sharma,28,amit@gmail.com,50000,Developer,Mumbai,0,57
5,Karan Mehta,35,karan@gmail.com,80000,Manager,Hyderabad,1,71
6,Sneha Patel,27,sneha@gmail.com,48000,Designer,Pune,0,55
7,Rahul Singh,25,rahul@gmail.com,45000,Developer,Delhi,0,51
8,Vikram Joshi,40,vikram@gmail.com,90000,Director,Chennai,1,81
9,Anjali Rao,31,anjali@gmail.com,62000,Analyst,Mumbai,1,63

In [198]:
# ### Q85. Group data using `groupby()`.
# > 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.
df10.groupby("job")["salary"].mean()

job
Analyst      63500.0
Designer     48000.0
Developer    47500.0
Director     90000.0
Manager      67500.0
Name: salary, dtype: float64

In [200]:
# ### Q86. Calculate sum per group.
# > 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.
df10.groupby("job")["salary"].sum()

job
Analyst      127000
Designer      48000
Developer    190000
Director      90000
Manager      135000
Name: salary, dtype: int64

In [202]:
# ### Q87. Calculate multiple aggregations.
# > 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.
df10.groupby("job").agg({"age": "mean", "salary": "sum"})

            age  salary
job
Analyst    31.5  127000
Designer   27.0   48000
Developer  26.5  190000
Director   40.0   90000
Manager    32.0  135000

In [203]:
# ### Q88. Group by multiple columns.
# > 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.
df10.groupby(["job","location"])["salary"].mean()

job        location
Analyst    Mumbai       62000.0
           Pune         65000.0
Designer   Pune         48000.0
Developer  Delhi        45000.0
           Mumbai       50000.0
Director   Chennai      90000.0
Manager    Bangalore    55000.0
           Hyderabad    80000.0
Name: salary, dtype: float64

In [204]:
# ### Q89. Filter grouped data.
# > 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.
df10.groupby("job").filter(lambda g: g["salary"].mean() > 50000)

           name  age             email  salary       job   location  flag  new
1   Priya Verma   32   priya@gmail.com   65000   Analyst       Pune     1   65
3    Neha Gupta   29    neha@gmail.com   55000   Manager  Bangalore     0   59
5   Karan Mehta   35   karan@gmail.com   80000   Manager  Hyderabad     1   71
8  Vikram Joshi   40  vikram@gmail.com   90000  Director    Chennai     1   81
9    Anjali Rao   31  anjali@gmail.com   62000   Analyst     Mumbai     1   63

In [206]:
# ### Q90. Transform grouped data using `transform()`.
# > 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.
df10.groupby("job")["salary"].transform("mean")

0    47500.0
1    63500.0
2    47500.0
3    67500.0
4    47500.0
5    67500.0
6    48000.0
7    47500.0
8    90000.0
9    63500.0
Name: salary, dtype: float64

In [208]:
# ### Q91. Apply custom function in groupby.
# > 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.
df10.groupby("job")["salary"].agg(lambda s: s.max() - s.min())

job
Analyst       3000
Designer         0
Developer     5000
Director         0
Manager      25000
Name: salary, dtype: int64

In [214]:
df6 = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "East", "East", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B", "A", "B"],
    "Salesperson": ["John", "John", "Mary", "Mary", "David", "David", "Sarah", "Sarah"],
    "Units": [10, 15, 20, 12, 18, 13, 25, 10],
    "Sales": [1000, 1500, 2000, 1200, 1800, 1300, np.nan, 1000]
})
df6

  Region Product Salesperson  Units   Sales
0  North       A        John     10  1000.0
1  North       B        John     15  1500.0
2  South       A        Mary     20  2000.0
3  South       B        Mary     12  1200.0
4   East       A       David     18  1800.0
5   East       B       David     13  1300.0
6   West       A       Sarah     25     NaN
7   West       B       Sarah     10  1000.0

In [215]:
# ### Q92. Create basic pivot table.
# > 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.
pd.pivot_table(df6, values="Sales", index="Region", columns="Product", aggfunc="mean")

Product       A       B
Region
East     1800.0  1300.0
North    1000.0  1500.0
South    2000.0  1200.0
West        NaN  1000.0

In [216]:
# ### Q93. Use multiple aggregation functions in pivot.
# > 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.
pd.pivot_table(df6, values="Sales", index="Region", columns="Product", aggfunc=["mean","max"])

           mean             max
Product       A       B       A       B
Region
East     1800.0  1300.0  1800.0  1300.0
North    1000.0  1500.0  1000.0  1500.0
South    2000.0  1200.0  2000.0  1200.0
West        NaN  1000.0     NaN  1000.0

In [219]:
# ### Q94. Handle missing values in pivot tables.
# > 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.
pd.pivot_table(df6, values="Sales", index="Region", columns="Product", aggfunc=["mean","max"],fill_value=1000)

           mean             max
Product       A       B       A       B
Region
East     1800.0  1300.0  1800.0  1300.0
North    1000.0  1500.0  1000.0  1500.0
South    2000.0  1200.0  2000.0  1200.0
West     1000.0  1000.0  1000.0  1000.0

In [227]:
# ### Q95. Add margins (totals) in pivot tables.
# > 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.
pd.pivot_table(df6, values="Sales", index="Region", columns="Product" ,fill_value=1000, aggfunc=["sum","max"],margins=True)

            sum                     max
Product       A       B     All       A       B     All
Region
East     1800.0  1300.0  3100.0  1800.0  1300.0  1800.0
North    1000.0  1500.0  2500.0  1000.0  1500.0  1500.0
South    2000.0  1200.0  3200.0  2000.0  1200.0  2000.0
West        0.0  1000.0  1000.0  1000.0  1000.0  1000.0
All      4800.0  5000.0  9800.0  2000.0  1500.0  2000.0

In [223]:
# ### Q96. Create multi-level pivot table.
# > 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.
pd.pivot_table(df6, values="Sales", index=["Region",'Salesperson'], columns="Product", aggfunc=["mean","max"],fill_value=1000)

                      mean             max
Product                  A       B       A       B
Region Salesperson
East   David        1800.0  1300.0  1800.0  1300.0
North  John         1000.0  1500.0  1000.0  1500.0
South  Mary         2000.0  1200.0  2000.0  1200.0
West   Sarah        1000.0  1000.0  1000.0  1000.0

In [224]:
# ### Q97. Convert DataFrame to pivot format.
# > 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).
df6.pivot(index="Region", columns="Product", values="Sales")

Product       A       B
Region
East     1800.0  1300.0
North    1000.0  1500.0
South    2000.0  1200.0
West        NaN  1000.0

In [240]:
# ### Q98. Compare pivot vs groupby.
# > 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.
group_data=df6.groupby('Region').sum()
print(group_data)

pivot_table_data=pd.pivot_table(df6, values="Sales", index="Region", columns="Product", aggfunc="sum",margins=True,margins_name='Total')

pivot_data=df6.pivot(index="Region", columns="Product", values="Sales")

       Product Salesperson  Units   Sales
Region
East        AB  DavidDavid     31  3100.0
North       AB    JohnJohn     25  2500.0
South       AB    MaryMary     32  3200.0
West        AB  SarahSarah     35  1000.0

In [232]:
# ### Q99. Build summary report using pivot table.
# > 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

r=pd.pivot_table(df6, values="Sales", index="Region", columns="Product" ,fill_value=1000, aggfunc=["sum","max"],margins=True).round(2)
r.to_csv("summary_report.csv")

In [108]:
# ### Q100. Create an end-to-end analysis workflow.
# > 💡 **Hint:** Follow this pipeline:  
# > 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.