In [1]:
import numpy as np
import pandas as pd

In [2]:
# ### NP1. Create a NumPy array and convert it to a Pandas Series.
# > 💡 **Hint:** `np.array([...])` creates the array. Pass it directly to `pd.Series(array, index=[...], name="...")`.

arr1=np.array([1,2,3,4,5,6])
s1=pd.Series(arr1)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
# ### NP2. Convert a 2D NumPy array to a Pandas DataFrame.
# > 💡 **Hint:** `pd.DataFrame(np_2d_array, columns=[...])` — shape `(n, m)` gives `n` rows and `m` columns.
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
df2=pd.DataFrame(arr2,columns=['a','b','c'])
df2

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
# ### NP3. Generate a random dataset using NumPy and store it in a DataFrame.
# > 💡 **Hint:** Use `np.random.seed()` for reproducibility. Try `np.random.randn(n, m)` for normal distribution or `np.random.randint(lo, hi, n)` for integers.
np.random.seed(15)
a3=np.random.randint(1,100,20).reshape(5,4)
df3=pd.DataFrame(a3,columns=[10,20,30,40])
df3

   10  20  30  40
0  73  13   6   1
1  29  28  72  76
2  86  48  94  18
3  32  24  33  63
4  11  16  69  40

In [5]:

# ### NP4. Perform element-wise operations using NumPy and Pandas.
# > 💡 **Hint:** You can apply NumPy ufuncs directly on a Pandas Series: `np.sqrt(df["col"])`. The result is a Series.
print(np.power(df3[10],2))
print(np.multiply(df3[10],100))

0    5329
1     841
2    7396
3    1024
4     121
Name: 10, dtype: int32
0    7300
1    2900
2    8600
3    3200
4    1100
Name: 10, dtype: int32

In [6]:
# ### NP5. Apply `np.mean` on DataFrame columns.
# > 💡 **Hint:** `np.mean(df["col"])` works the same as `df["col"].mean()`. Apply to the `.values` array for pure NumPy speed: `np.mean(df["col"].values)`.
import time
start=time.time()
print(np.mean(df3[10]))
t=time.time()-start

start1=time.time()
print(df3[10].mean())
t1=time.time()-start1

start2=time.time()
print(np.mean(df3[10].values))
t2=time.time()-start2

print(t,'  ',t1,'  ',t2)

46.2
46.2
46.2
0.002260923385620117    0.0004899501800537109    0.0003578662872314453

In [7]:
# ### NP6. Replace values using `np.where`.
# > 💡 **Hint:** `np.where(condition, value_if_true, value_if_false)` — assign the result back to a column: `df["col"] = np.where(df["col"] > 50, "High", "Low")`.

df3[10] = np.where(df3[10] > 50, "High", "Low")
df3

     10  20  30  40
0  High  13   6   1
1   Low  28  72  76
2  High  48  94  18
3   Low  24  33  63
4   Low  16  69  40

In [8]:
# ### NP7. Apply logarithmic transformation using `np.log`.
# > 💡 **Hint:** `df["col_log"] = np.log(df["col"])`. Note: `np.log(0)` returns `-inf`. Use `np.log1p(x)` which computes `log(1 + x)` to safely handle zeros.

df3["20_log"] = np.log(df3[20])
df3

     10  20  30  40    20_log
0  High  13   6   1  2.564949
1   Low  28  72  76  3.332205
2  High  48  94  18  3.871201
3   Low  24  33  63  3.178054
4   Low  16  69  40  2.772589

In [9]:
# ### NP8. Apply square root transformation using `np.sqrt`.
# > 💡 **Hint:** `df["col_sqrt"] = np.sqrt(df["col"])`. Values must be non-negative; use `np.clip(df["col"], 0, None)` first if negatives are possible.

df3["20_sqrt"] = np.sqrt(df3[20])
df3

     10  20  30  40    20_log   20_sqrt
0  High  13   6   1  2.564949  3.605551
1   Low  28  72  76  3.332205  5.291503
2  High  48  94  18  3.871201  6.928203
3   Low  24  33  63  3.178054  4.898979
4   Low  16  69  40  2.772589  4.000000

In [10]:
# ### NP9. Use NumPy functions inside `apply()`.
# > 💡 **Hint:** `df["col"].apply(lambda x: np.log(x))` — or pass the NumPy function directly: `df["col"].apply(np.log)`.
df3["30_log"]=df3[30].apply(lambda x: np.log(x))
df3

     10  20  30  40    20_log   20_sqrt    30_log
0  High  13   6   1  2.564949  3.605551  1.791759
1   Low  28  72  76  3.332205  5.291503  4.276666
2  High  48  94  18  3.871201  6.928203  4.543295
3   Low  24  33  63  3.178054  4.898979  3.496508
4   Low  16  69  40  2.772589  4.000000  4.234107

In [11]:

# ### NP10. Perform broadcasting in a DataFrame using NumPy.
# > 💡 **Hint:** Extract `.values` (a 2D NumPy array) and multiply by a weights array: `df[cols].values @ weights_array`. The result can be assigned back as a new column.

df = pd.DataFrame({
    'math': [80, 90, 70],
    'science': [85, 88, 75],
    'english': [78, 92, 80]
})
weights = np.array([0.40, 0.35, 0.25])
cols = df.columns
df['weighted_score'] = df[cols].values @ weights
print(df)

   math  science  english  weighted_score
0    80       85       78           81.25
1    90       88       92           89.80
2    70       75       80           74.25

In [12]:
# ### NP11. Filter DataFrame rows using a NumPy boolean mask.
# > 💡 **Hint:** `mask = np.array(df["col"]) > threshold` creates a NumPy boolean array. Use `df[mask]` to filter.
mask=np.array(df3[20])>20
print(mask)
df3[mask]

[False  True  True  True False]

     10  20  30  40    20_log   20_sqrt    30_log
1   Low  28  72  76  3.332205  5.291503  4.276666
2  High  48  94  18  3.871201  6.928203  4.543295
3   Low  24  33  63  3.178054  4.898979  3.496508

In [13]:
# ### NP12. Count non-zero values in a column using NumPy.
# > 💡 **Hint:** `np.count_nonzero(df["col"].values)` or `np.count_nonzero(df["col"].values != 0)`.
dict={'a':[1,2,np.nan,0,np.nan,4,5,np.nan],'b':[8,9,9,np.nan,np.nan,6,4,8]}
df4=pd.DataFrame(dict)
print(np.count_nonzero(df4['a']))

7

In [14]:
# ### NP13. Find unique values using `np.unique`.
# > 💡 **Hint:** `np.unique(df["col"])` returns sorted unique values. Use `return_counts=True` to also get the frequency of each unique value.
print(np.unique(df4["b"],return_counts=True))

(array([ 4.,  6.,  8.,  9., nan]), array([1, 1, 2, 2, 2]))

In [93]:
# ### NP14. Flatten DataFrame values to a 1D NumPy array.
# > 💡 **Hint:** `df[["col1","col2"]].values.flatten()` — the `.flatten()` method converts the 2D array to 1D row-by-row.

print(df4)
print(df4[["a","b"]].values.flatten())

     a    b
0  1.0  8.0
1  2.0  9.0
2  NaN  9.0
3  0.0  NaN
4  NaN  NaN
5  4.0  6.0
6  5.0  4.0
7  NaN  8.0
[ 1.  8.  2.  9. nan  9.  0. nan nan nan  4.  6.  5.  4. nan  8.]

In [16]:
# ### NP15. Reshape a NumPy array before creating a DataFrame.
# > 💡 **Hint:** `np.arange(1, 25).reshape(6, 4)` creates a 6×4 array. Pass directly to `pd.DataFrame(arr, columns=[...])`.
a15=np.arange(1, 25).reshape(6, 4)
df5=pd.DataFrame(a15,columns=['a','b','c','d'])
df5

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

In [17]:
# ### NP16. Perform matrix multiplication using `np.dot`.
# > 💡 **Hint:** `np.dot(A, B)` or `A @ B`. Extract `.values` from DataFrames first, then wrap the result in a new `pd.DataFrame(result, columns=[...])`.

a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
r1=a @ b
print(r1)

dfa=pd.DataFrame(a)
dfb=pd.DataFrame(b)
r2=np.dot(dfa.values, dfb.values)
dfr2=pd.DataFrame(r2)
dfr2

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

     0    1    2
0   90   96  102
1  216  231  246
2  342  366  390

In [18]:
# ### NP17. Normalize data using NumPy (Min-Max scaling).
# > 💡 **Hint:** `arr = df[cols].values` then `(arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))`. Use `axis=0` to operate column-wise.
arr=df5['a'].values
r=(arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))
print(r)

[0.  0.2 0.4 0.6 0.8 1. ]

In [19]:
# ### NP18. Standardize data using Z-score with NumPy.
# > 💡 **Hint:** `z = (arr - arr.mean(axis=0)) / arr.std(axis=0)`. Wrap the result in a DataFrame using the original column names.
z = (arr - arr.mean(axis=0)) / arr.std(axis=0)
df5['a']=z
df5

         a   b   c   d
0 -1.46385   2   3   4
1 -0.87831   6   7   8
2 -0.29277  10  11  12
3  0.29277  14  15  16
4  0.87831  18  19  20
5  1.46385  22  23  24

In [20]:
# ### NP19. Clip values using `np.clip`.
# > 💡 **Hint:** `np.clip(df["col"].values, a_min=lower_bound, a_max=upper_bound)` — values outside the range are replaced by the boundary values.
print(dfr2[2])
np.clip(dfr2[2].values, a_min=150, a_max=300)

0    102
1    246
2    390
Name: 2, dtype: int64

array([150, 246, 300])

In [21]:
# ### NP20. Handle missing values using NumPy.
# > 💡 **Hint:** Detect NaN with `np.isnan(arr)`. Fill using `np.nanmean(arr)` to compute the mean ignoring NaN, then replace: `arr[np.isnan(arr)] = np.nanmean(arr)`.
a20=np.array([1,2,np.nan,3,5,np.nan])
r1=np.isnan(a20)
nmean=np.nanmean(a20)
a20[np.isnan(a20)]=nmean
a20

array([1.  , 2.  , 2.75, 3.  , 5.  , 2.75])

In [22]:
# ### NP21. Compare NumPy vs Pandas performance on a large array.
# > 💡 **Hint:** Use `time.time()` before and after each operation. Apply the same computation (`arr * 2 + 1`) to a raw NumPy array and a Pandas Series. NumPy is typically faster on pure numeric operations.

a21=np.random.randint(1,1000,5000)
start1=time.time()
a21*2+1
t1=time.time()-start1

s1=pd.Series(a21)
start2=time.time()
s1*2+1
t2=time.time()-start2

print(t1,'   ',t2)

0.0009024143218994141     0.001384735107421875

In [23]:
# ### NP22. Calculate cumulative sum using NumPy.
# > 💡 **Hint:** `np.cumsum(df["col"].values)` — assign back: `df["cum_col"] = np.cumsum(df["col"])`.
np.cumsum(df5["b"].values)
df5["cum_b"] = np.cumsum(df5["b"])
df5

         a   b   c   d  cum_b
0 -1.46385   2   3   4      2
1 -0.87831   6   7   8      8
2 -0.29277  10  11  12     18
3  0.29277  14  15  16     32
4  0.87831  18  19  20     50
5  1.46385  22  23  24     72

In [24]:
# ### NP23. Use `np.argmax` and `np.argmin`.
# > 💡 **Hint:** `np.argmax(df["col"].values)` returns the **integer position** of the maximum. Use `df.iloc[idx]` or `df.loc[idx]` to retrieve the full row.
idx=np.argmax(df5["b"].values)
df5.iloc[idx]

a         1.46385
b        22.00000
c        23.00000
d        24.00000
cum_b    72.00000
Name: 5, dtype: float64

In [25]:
# ### NP24. Sort values using NumPy `np.argsort`.
# > 💡 **Hint:** `sorted_idx = np.argsort(df["col"].values)` gives indices that would sort the array. Use `df.iloc[sorted_idx]` to reorder the DataFrame.

sorted_idx = np.argsort(df5["b"].values)
df5['b'].iloc[sorted_idx]

0     2
1     6
2    10
3    14
4    18
5    22
Name: b, dtype: int64

In [26]:
# ### NP25. Compute correlation using `np.corrcoef`.
# > 💡 **Hint:** `np.corrcoef([df["col1"].values, df["col2"].values])` returns a 2×2 correlation matrix. Wrap in a DataFrame for readability. Compare with `df.corr()`.
np.corrcoef([df5["b"].values, df5["c"].values])

array([[1., 1.],
       [1., 1.]])

In [27]:
# ### NP26. Detect NaN values using NumPy.
# > 💡 **Hint:** `np.isnan(arr)` returns a boolean array. Count NaN with `np.isnan(arr).sum()`. Compare with `pd.isnull(series)`.
a26=np.array([1,2,np.nan,3,5,np.nan])
print(np.isnan(a26))
print(np.isnan(a26).sum())

s26=pd.Series(a26)
print(pd.isnull(s26))

[False False  True False False  True]
2
0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [28]:
# ### NP27. Create boolean masks using NumPy.
# > 💡 **Hint:** `mask = (np.array(df["col1"]) > 80) & (np.array(df["col2"]) < 40)` — use `df[mask]` to filter.

mask = (np.array(df3[20]) > 20) & (np.array(df3[30]) < 40)
df3[mask]

    10  20  30  40    20_log   20_sqrt    30_log
3  Low  24  33  63  3.178054  4.898979  3.496508

In [29]:
# ### NP28. Apply logical operations (`np.logical_and`, `np.logical_or`, `np.logical_not`).
# > 💡 **Hint:** `np.logical_and(cond1, cond2)` is equivalent to `cond1 & cond2`. These functions work on NumPy arrays; convert Series with `.values` first.
np.logical_and(df3[20].values > 20, df3[30].values <40)

array([False, False, False,  True, False])

In [30]:
# ### NP29. Apply `np.select` for multi-condition assignment.
# > 💡 **Hint:** `df["Grade"] = np.select([df["Score"] >= 90, df["Score"] >= 75], ["A","B"], default="C")` — conditions are checked in order; the first match wins.
student_mark=[[67,56,54,56,55],
              [63,65,67,48,78],
              [89,56,27,48,62],
              [98,85,75,95,84]]

df1=pd.DataFrame(student_mark,columns=['hindi','english','science','maths','sst'])
df1
df1["Grade_Maths"] = np.select([df1["maths"] >= 90, df1["maths"] >= 50], ["A","B"], default="C")
df1

   hindi  english  science  maths  sst Grade_Maths
0     67       56       54     56   55           B
1     63       65       67     48   78           C
2     89       56       27     48   62           C
3     98       85       75     95   84           A

In [31]:
# ### NP30. Multiply DataFrame columns element-wise using NumPy.
# > 💡 **Hint:** `np.multiply(df["col1"].values, df["col2"].values)` is equivalent to `df["col1"] * df["col2"]` but uses NumPy internally.
print(df5)
np.multiply(df5["b"].values, df5["c"].values)

         a   b   c   d  cum_b
0 -1.46385   2   3   4      2
1 -0.87831   6   7   8      8
2 -0.29277  10  11  12     18
3  0.29277  14  15  16     32
4  0.87831  18  19  20     50
5  1.46385  22  23  24     72

array([  6,  42, 110, 210, 342, 506])

In [32]:
# ### NP31. Shuffle dataset rows using NumPy.
# > 💡 **Hint:** `shuffled_idx = np.random.permutation(df.index)` creates a random permutation of row indices. Use `df.loc[shuffled_idx].reset_index(drop=True)`.
print(df3)
shuffled_idx = np.random.permutation(df3.index)
print(shuffled_idx)
print(df3)

df3.loc[shuffled_idx].reset_index(drop=True)

     10  20  30  40    20_log   20_sqrt    30_log
0  High  13   6   1  2.564949  3.605551  1.791759
1   Low  28  72  76  3.332205  5.291503  4.276666
2  High  48  94  18  3.871201  6.928203  4.543295
3   Low  24  33  63  3.178054  4.898979  3.496508
4   Low  16  69  40  2.772589  4.000000  4.234107
[4 1 0 2 3]
     10  20  30  40    20_log   20_sqrt    30_log
0  High  13   6   1  2.564949  3.605551  1.791759
1   Low  28  72  76  3.332205  5.291503  4.276666
2  High  48  94  18  3.871201  6.928203  4.543295
3   Low  24  33  63  3.178054  4.898979  3.496508
4   Low  16  69  40  2.772589  4.000000  4.234107

     10  20  30  40    20_log   20_sqrt    30_log
0   Low  16  69  40  2.772589  4.000000  4.234107
1   Low  28  72  76  3.332205  5.291503  4.276666
2  High  13   6   1  2.564949  3.605551  1.791759
3  High  48  94  18  3.871201  6.928203  4.543295
4   Low  24  33  63  3.178054  4.898979  3.496508

In [33]:
# ### NP32. Sample random rows using NumPy.
# > 💡 **Hint:** `sample_idx = np.random.choice(df.index, size=N, replace=False)` — use `df.loc[sample_idx]`. Compare with `df.sample(N)`.

sample_idx = np.random.choice(df3.index, size=4, replace=False)
print(sample_idx)
df3.loc[sample_idx]
print(df3.sample(4))

[2 3 1 0]
     10  20  30  40    20_log   20_sqrt    30_log
3   Low  24  33  63  3.178054  4.898979  3.496508
2  High  48  94  18  3.871201  6.928203  4.543295
4   Low  16  69  40  2.772589  4.000000  4.234107
0  High  13   6   1  2.564949  3.605551  1.791759

In [34]:
# ### NP33. Calculate percentiles using NumPy.
# > 💡 **Hint:** `np.percentile(df["col"].values, [25, 50, 75])` returns Q1, median, Q3. Use `np.percentile(arr, p)` for any percentile p in [0, 100].
print(df3)
q1,q2,q3 = np.percentile(df3[40].values, [25, 50, 75])
print(q1,q2,q3)

     10  20  30  40    20_log   20_sqrt    30_log
0  High  13   6   1  2.564949  3.605551  1.791759
1   Low  28  72  76  3.332205  5.291503  4.276666
2  High  48  94  18  3.871201  6.928203  4.543295
3   Low  24  33  63  3.178054  4.898979  3.496508
4   Low  16  69  40  2.772589  4.000000  4.234107
18.0 40.0 63.0

In [35]:
# ### NP34. Calculate variance and standard deviation.
# > 💡 **Hint:** `np.var(arr)` and `np.std(arr)` use `ddof=0` (population). Pandas `.var()` and `.std()` use `ddof=1` (sample). Be aware of this difference when comparing results.
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.var(arr))
print(np.std(arr))
df34=pd.DataFrame(arr)
print(df34[0].var())
print(df34[0].std())
print(df34[0].var(ddof=0))
print(df34[0].std(ddof=0))

6.666666666666667
2.581988897471611
7.5
2.7386127875258306
6.666666666666667
2.581988897471611

In [36]:
# ### NP35. Replace a DataFrame column with a NumPy array.
# > 💡 **Hint:** `df["col"] = new_numpy_array` — the array length must match the number of rows. NumPy arrays are accepted directly.
arr=np.array([1,2,3,6,5])
df3[50] = arr 
df3

     10  20  30  40    20_log   20_sqrt    30_log  50
0  High  13   6   1  2.564949  3.605551  1.791759   1
1   Low  28  72  76  3.332205  5.291503  4.276666   2
2  High  48  94  18  3.871201  6.928203  4.543295   3
3   Low  24  33  63  3.178054  4.898979  3.496508   6
4   Low  16  69  40  2.772589  4.000000  4.234107   5

In [37]:
# ### NP36. Convert DataFrame to NumPy using `to_numpy()`.
# > 💡 **Hint:** `df[["col1","col2"]].to_numpy()` returns a 2D NumPy array. This is the preferred method over `.values` as it accepts `dtype` and `na_value` parameters.
r1=df3[[20,30]].to_numpy()
r1

array([[13,  6],
       [28, 72],
       [48, 94],
       [24, 33],
       [16, 69]], dtype=int32)

In [38]:
# ### NP37. Compare `.values` vs `.to_numpy()`.
# > 💡 **Hint:** Both return a NumPy array. Key difference: `.to_numpy(dtype=np.float32)` accepts a `dtype` argument for explicit casting. Use `np.array_equal(a, b)` to confirm they produce the same result.
r2=df3[[20,30]].values
r2
np.array_equal(r1, r2)

True

In [39]:
# ### NP38. Slice a column using NumPy array indexing.
# > 💡 **Hint:** Extract with `.values`, then apply NumPy slicing: `arr[::2]` (every other element), `arr[::-1]` (reversed), `arr[[0,3,5]]` (fancy indexing).
print(r2[::2])
print(r2[::-1])
print(r2[[0,3,4]])

[[13  6]
 [48 94]
 [16 69]]
[[16 69]
 [24 33]
 [48 94]
 [28 72]
 [13  6]]
[[13  6]
 [24 33]
 [16 69]]

In [40]:
# ### NP39. Merge NumPy-generated data into a DataFrame.
# > 💡 **Hint:** Create two DataFrames from NumPy arrays with a common key column (e.g., `ID`). Use `pd.merge(df1, df2, on="ID", how="outer")`.
dict1={'id':[101,102,103,104,105,106,107,108],'name':['a','b','c','d','e','f','g','h']}
dict2={'id':[101,102,103,104,105,106,107,108],'salary': [10000,12000,15000,14000,9000,4500,60000,90000]}
dfa=pd.DataFrame(dict1)
dfb=pd.DataFrame(dict2)
r=pd.merge(dfa, dfb, on="id", how="outer")
r

    id name  salary
0  101    a   10000
1  102    b   12000
2  103    c   15000
3  104    d   14000
4  105    e    9000
5  106    f    4500
6  107    g   60000
7  108    h   90000

In [41]:
# ### NP40. Apply rolling computation using NumPy.
# > 💡 **Hint:** Use a list comprehension: `[np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))]` to manually compute a rolling mean with window `w`. Compare with `df["col"].rolling(w).mean()`.

arr=np.array([10000,12000,15000,14000,9000,4500,60000,90000])
w=3
rmean=[np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))]
print(rmean)
r2=r["salary"].rolling(3).mean()
print(r2)

[np.float64(10000.0), np.float64(11000.0), np.float64(12333.333333333334), np.float64(13666.666666666666), np.float64(12666.666666666666), np.float64(9166.666666666666), np.float64(24500.0), np.float64(51500.0)]
0             NaN
1             NaN
2    12333.333333
3    13666.666667
4    12666.666667
5     9166.666667
6    24500.000000
7    51500.000000
Name: salary, dtype: float64

In [83]:
# ### NP41. Create a synthetic ML dataset using NumPy.
# > 💡 **Hint:** Use `np.random.normal`, `np.random.randint`, `np.random.choice` to generate features. Use `np.where` or `np.select` to create a binary/multi-class label column.
np.random.seed(41)
df41=pd.DataFrame({'name':['nitish','ankit','pranav','yash','mayuri','mohit','ankita','kaveri'],'courses':np.random.choice(10,8)
                   ,'marks':np.random.normal(loc=80,scale=10,size=8)})
df41['cutoff']=np.where(df41['marks']>80,'qualified','not qualified')
df41

     name  courses      marks         cutoff
0  nitish        0  87.778654      qualified
1   ankit        3  90.110892      qualified
2  pranav        2  84.343707      qualified
3    yash        0  84.803444      qualified
4  mayuri        1  78.380743  not qualified
5   mohit        3  66.898526  not qualified
6  ankita        9  87.266209      qualified
7  kaveri        7  83.827819      qualified

In [75]:
# ### NP42. Detect and replace outliers using NumPy.
# > 💡 **Hint:** Compute Q1, Q3 with `np.percentile`. Define bounds as `Q1 - 1.5*IQR` and `Q3 + 1.5*IQR`. Use `np.clip(arr, lo, hi)` to replace outliers with boundary values.
a42=np.array([10,2500,6000,4522,9645,7532,1533,1400,896655,5632,7895466,0,2])
Q1=np.percentile(a42,25)
Q3=np.percentile(a42,75)
print(Q1,Q3)
IQR= Q3 - Q1
print(IQR)
l_f=Q1 - 1.5*IQR
u_f=Q3 + 1.5*IQR
print(l_f,u_f)
r=np.clip(a42,l_f,u_f)
r

1400.0 7532.0
6132.0
-7798.0 16730.0

array([1.000e+01, 2.500e+03, 6.000e+03, 4.522e+03, 9.645e+03, 7.532e+03,
       1.533e+03, 1.400e+03, 1.673e+04, 5.632e+03, 1.673e+04, 0.000e+00,
       2.000e+00])

In [87]:
# ### NP43. Scale dataset using NumPy functions.
# > 💡 **Hint:** Apply Min-Max or Z-score scaling using NumPy on the `.values` array. Store results as new columns in the DataFrame.
df41['min-max_scale']=(df41['marks']-df41['marks'].min())/(df41['marks'].max()-df41['marks'].min())
df41['zscore']=(df41['marks']-df41['marks'].mean())/df41['marks'].std()
df41

     name  courses      marks         cutoff  min-max_scale    zscore
0  nitish        0  87.778654      qualified       0.899526  0.660420
1   ankit        3  90.110892      qualified       1.000000  0.977841
2  pranav        2  84.343707      qualified       0.751547  0.192918
3    yash        0  84.803444      qualified       0.771353  0.255489
4  mayuri        1  78.380743  not qualified       0.494660 -0.618650
5   mohit        3  66.898526  not qualified       0.000000 -2.181398
6  ankita        9  87.266209      qualified       0.877450  0.590675
7  kaveri        7  83.827819      qualified       0.729322  0.122705

In [45]:
# ### NP44. Engineer new features using NumPy.
# > 💡 **Hint:** Create polynomial features (`np.square`, `np.power`), log features (`np.log1p`), interaction features (column1 × column2), and binned features (`np.digitize`).
a42
print(np.square(dfa['id']))
print(np.power(dfa['id'],2))
print(np.log1p(dfa['id']))
print(dfa['id']*dfb['id'])
print(np.digitize(dfb['salary'],[1000,5000,9000,13000,17000]))

0    10201
1    10404
2    10609
3    10816
4    11025
5    11236
6    11449
7    11664
Name: id, dtype: int64
0    10201
1    10404
2    10609
3    10816
4    11025
5    11236
6    11449
7    11664
Name: id, dtype: int64
0    4.624973
1    4.634729
2    4.644391
3    4.653960
4    4.663439
5    4.672829
6    4.682131
7    4.691348
Name: id, dtype: float64
0    10201
1    10404
2    10609
3    10816
4    11025
5    11236
6    11449
7    11664
Name: id, dtype: int64
[3 3 4 4 3 1 5 5]

In [46]:
# ### NP45. Use exponential functions (`np.exp`).
# > 💡 **Hint:** `np.exp(df["col"])` computes `e^x` for each element. This is the inverse of `np.log`. Useful for reverting log-transformed values.
print(np.exp(dfa['id']))

0    7.307060e+43
1    1.986265e+44
2    5.399228e+44
3    1.467662e+45
4    3.989520e+45
5    1.084464e+46
6    2.947878e+46
7    8.013164e+46
Name: id, dtype: float64

In [64]:
# ### NP46. Compute differences using `np.diff`.
# > 💡 **Hint:** `np.diff(df["col"].values)` returns an array of consecutive differences (length = n−1). Prepend `np.nan` and assign back: `df["col_diff"] = np.insert(np.diff(arr), 0, np.nan)`.

x=np.diff(dfb['salary'].values)
x=x.astype(np.float32)
print(x)
print(x.dtype)
dfb['salary_diff']= np.insert(x, 0, np.nan)
dfb

[ 2000.  3000. -1000. -5000. -4500. 55500. 30000.]
float32

    id  salary  salary_diff
0  101   10000          NaN
1  102   12000       2000.0
2  103   15000       3000.0
3  104   14000      -1000.0
4  105    9000      -5000.0
5  106    4500      -4500.0
6  107   60000      55500.0
7  108   90000      30000.0

In [90]:
# ### NP47. Apply conditional encoding using NumPy.
# > 💡 **Hint:** Use `np.select` with a list of conditions and corresponding integer codes to encode categorical columns numerically. For example: `DS → 0`, `ML → 1`, `AI → 2`.
df47 = pd.DataFrame({
    'name': [
        'Aarav', 'Vivaan', 'Aditya', 'Arjun', 'Krishna',
        'Ananya', 'Diya', 'Priya', 'Kavya', 'Sneha',
        'Rahul', 'Rohit', 'Neha', 'Pooja', 'Aisha'
    ],
    'courses': [
        'DS', 'ML', 'AI', 'DS', 'ML',
        'AI', 'DS', 'ML', 'AI', 'DS',
        'ML', 'AI', 'DS', 'ML', 'AI'
    ],
    'age': [
        22, 24, 23, 25, 21,
        22, 23, 24, 21, 25,
        26, 23, 22, 24, 21
    ],
    'score': [
        88, 91, 85, 79, 95,
        87, 90, 84, 92, 89,
        78, 94, 86, 88, 93
    ]
})
df47['code']=np.select([df47['courses']=='DS',df47['courses']=='ML',df47['courses']=='AI'],[0,1,2])
df47

       name courses  age  score  code
0     Aarav      DS   22     88     0
1    Vivaan      ML   24     91     1
2    Aditya      AI   23     85     2
3     Arjun      DS   25     79     0
4   Krishna      ML   21     95     1
5    Ananya      AI   22     87     2
6      Diya      DS   23     90     0
7     Priya      ML   24     84     1
8     Kavya      AI   21     92     2
9     Sneha      DS   25     89     0
10    Rahul      ML   26     78     1
11    Rohit      AI   23     94     2
12     Neha      DS   22     86     0
13    Pooja      ML   24     88     1
14    Aisha      AI   21     93     2

In [49]:
# ### NP48. Build an ML-ready dataset (feature matrix X and label vector y).
# > 💡 **Hint:** Select numeric feature columns → call `.to_numpy(dtype=np.float32)` → store as `X`. Create a binary label: `y = (df["col"] >= threshold).astype(int).to_numpy()`. Check shapes with `X.shape` and `y.shape`.

In [50]:
# ### NP49. Perform a mini data analysis project.
# > 💡 **Hint:** Follow these steps: (1) Generate data with NumPy, (2) Store in DataFrame, (3) Clean with Pandas, (4) Engineer features with NumPy, (5) GroupBy analysis, (6) Detect outliers, (7) Export summary.

In [51]:
# ### NP50. Build an end-to-end pipeline using NumPy + Pandas.
# > 💡 **Hint:** Chain all steps together:  
# > 1. `np.random.seed(X)` → generate raw data  
# > 2. `np.clip` → clean invalid values  
# > 3. `np.log`, `np.square`, `np.where` → feature engineering  
# > 4. `df.groupby().agg(...)` → statistical analysis  
# > 5. IQR + `np.clip` → outlier removal  
# > 6. `df[features].to_numpy(dtype=np.float32)` → ML feature matrix  
# > 7. Export with `df.to_csv(...)